import type { Metadata } from "next";
import "../globals.css";
import React from "react";
import { Providers } from "@/modules/shared/components/providers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body className={`antialiased`}>
          <Toaster position={"top-right"} />
          {children}
        </body>
      </Providers>
    </html>
  );
}
